"""init schema

Revision ID: 630a6dee2617
Revises: 
Create Date: 2025-09-10 14:46:37.088429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630a6dee2617'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.Enum('ea', 'drum', name='stock_unit'), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_sku'), 'stock_items', ['sku'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PM', 'SITE', 'SMME', 'AUDITOR', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pon_number', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('street_area', sa.String(length=255), nullable=True),
    sa.Column('homes_passed', sa.Integer(), nullable=True),
    sa.Column('poles_planned', sa.Integer(), nullable=True),
    sa.Column('poles_planted', sa.Integer(), nullable=True),
    sa.Column('cac_passed', sa.Boolean(), nullable=False),
    sa.Column('stringing_done', sa.Boolean(), nullable=False),
    sa.Column('photos_uploaded', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('smme_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['smme_id'], ['smmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pons_pon_number'), 'pons', ['pon_number'], unique=True)
    op.create_index(op.f('ix_pons_status'), 'pons', ['status'], unique=False)
    op.create_table('cac_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pon_id', sa.Integer(), nullable=False),
    sa.Column('pole_number', sa.String(), nullable=False),
    sa.Column('pole_length_m', sa.Float(), nullable=False),
    sa.Column('depth_m', sa.Float(), nullable=False),
    sa.Column('tag_height_m', sa.Float(), nullable=False),
    sa.Column('hook_position', sa.String(), nullable=True),
    sa.Column('alignment_ok', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('checked_by', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pon_id'], ['pons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cac_checks_pon_id'), 'cac_checks', ['pon_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pon_id', sa.Integer(), nullable=False),
    sa.Column('smme_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Submitted', 'Approved', 'Paid', name='invoice_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pon_id'], ['pons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['smme_id'], ['smmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_pon_id'), 'invoices', ['pon_id'], unique=False)
    op.create_table('stock_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('pon_id', sa.Integer(), nullable=True),
    sa.Column('issued_to', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issued_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['pon_id'], ['pons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stringing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pon_id', sa.Integer(), nullable=False),
    sa.Column('meters', sa.Integer(), nullable=False),
    sa.Column('brackets', sa.Integer(), nullable=False),
    sa.Column('dead_ends', sa.Integer(), nullable=False),
    sa.Column('tensioner', sa.Integer(), nullable=False),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pon_id'], ['pons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stringing_runs_pon_id'), 'stringing_runs', ['pon_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pon_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Enum('Wayleave', 'ServicesCheck', 'Kickoff', 'Permissions', 'PermissionsUpload', 'PolePlanting', 'PolePhotos', 'CAC', 'Stringing', 'StringingPhotos', 'HomeSignup', 'Installation', 'Activation', 'Invoicing', name='task_step'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('smme_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', 'FAILED', name='task_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pon_id'], ['pons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['smme_id'], ['smmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_pon_id'), 'tasks', ['pon_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pon_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pon_id'], ['pons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_pon_id'), 'photos', ['pon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_pon_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_tasks_pon_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_stringing_runs_pon_id'), table_name='stringing_runs')
    op.drop_table('stringing_runs')
    op.drop_table('stock_issues')
    op.drop_index(op.f('ix_invoices_pon_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_cac_checks_pon_id'), table_name='cac_checks')
    op.drop_table('cac_checks')
    op.drop_index(op.f('ix_pons_status'), table_name='pons')
    op.drop_index(op.f('ix_pons_pon_number'), table_name='pons')
    op.drop_table('pons')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_items_sku'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_table('smmes')
    # ### end Alembic commands ###
