changelog:
  exclude:
    labels: [ skip-changelog ]
  categories:
    - title: Features
      labels: [ feature, enhancement ]
    - title: Fixes
      labels: [ bug, fix ]
    - title: Ops
      labels: [ infra, ci ]

