version: '3.9'
services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
      CORS_ALLOW_ORIGINS: http://localhost:3000
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_BUCKET: fiber-photos
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio12345
      SUPABASE_URL: https://bigbujrinohnmoxuidbx.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZ2J1anJpbm9obm1veHVpZGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NzkxNTAsImV4cCI6MjA3MzE1NTE1MH0.LnszUQtZO9jCJfr5rSfPqGqYHWok6NjrOSWGh7NbdWw
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ["/bin/bash", "-lc", "uvicorn app.main:app --host 0.0.0.0 --port 8000"]
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  db-data:
  redis-data:
  minio-data:
