name: API Lint

on:
  push:
    paths:
      - 'app/**'
      - 'alembic/**'
  pull_request:
    paths:
      - 'app/**'
      - 'alembic/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.9

      - name: Lint app with ruff
        run: |
          ruff check app
