name: seed

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Seed sample data
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL || '' }}
        run: |
          if [[ -z "$DATABASE_URL" ]]; then echo "DATABASE_URL not set; skipping"; exit 0; fi
          python scripts/seed.py | cat
