name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Alembic upgrade head
        env:
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres
        run: |
          python - <<'PY'
          import os
          from sqlalchemy import create_engine
          from alembic.config import Config
          from alembic import command
          cfg = Config()
          cfg.set_main_option('script_location', 'alembic')
          cfg.set_main_option('sqlalchemy.url', os.environ['DATABASE_URL'])
          command.upgrade(cfg, 'head')
          PY
      - name: Run tests
        env:
          DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres
        run: |
          pytest -q --cov=app --cov-report=term-missing
