name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: app
          POSTGRES_DB: app
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U app -d app" --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
      minio:
        image: minio/minio:latest
        ports: ["9000:9000", "9001:9001"]
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio12345
        command: server /data --console-address ":9001"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for services
        run: |
          for i in {1..30}; do pg_isready -h localhost -U app -d app && break || sleep 2; done

      - name: Configure env
        run: |
          echo "DATABASE_URL=postgresql+psycopg2://app:postgres@localhost:5432/app" >> $GITHUB_ENV
          echo "REDIS_URL=redis://localhost:6379/0" >> $GITHUB_ENV
          echo "S3_ENDPOINT=http://localhost:9000" >> $GITHUB_ENV
          echo "S3_REGION=us-east-1" >> $GITHUB_ENV
          echo "S3_BUCKET=fiber-photos" >> $GITHUB_ENV
          echo "S3_ACCESS_KEY=minio" >> $GITHUB_ENV
          echo "S3_SECRET_KEY=minio12345" >> $GITHUB_ENV
          echo "JWT_SECRET=ci-secret" >> $GITHUB_ENV

      - name: DB migrate
        run: alembic upgrade head

      - name: Configure MinIO bucket
        run: python scripts/setup_minio.py

      - name: Lint import
        run: python -c "import app.main; print('import ok')"

      - name: Ready check
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          PID=$!
          for i in {1..30}; do curl -fsS http://127.0.0.1:8000/readyz && break || sleep 2; done
          kill $PID || true

name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install -r requirements.txt
          python -m pip install ruff black
          ruff check .
          black --check .

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: |
          cd client
          npm ci
          npm run build

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fiber
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=5s
          --health-timeout=5s --health-retries=5
      minio:
        image: minio/minio:latest
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123
        ports: ['9000:9000']
        options: >-
          --health-cmd="curl -f http://localhost:9000/minio/health/live || exit 1" --health-interval=5s
          --health-timeout=5s --health-retries=5
        command: server /data
    env:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/fiber
      JWT_SECRET: test_secret
      S3_ENDPOINT: http://localhost:9000
      S3_REGION: us-east-1
      S3_BUCKET: fiber-photos
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      CORS_ALLOW_ORIGINS: http://localhost:5173
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        if: ${{ secrets.SUPABASE_ACCESS_TOKEN != '' }}
        with:
          node-version: '20'
      - name: Supabase login (optional)
        if: ${{ secrets.SUPABASE_ACCESS_TOKEN != '' }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          npx --yes supabase@latest login --token "$SUPABASE_ACCESS_TOKEN"
      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Wait for Postgres
        run: |
          for i in {1..30}; do pg_isready -h localhost -U postgres && break || sleep 1; done
      - name: Prepare DB
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -c "CREATE DATABASE fiber;" || true
      - name: Alembic upgrade
        run: |
          source .venv/bin/activate
          alembic upgrade head
      - name: Lint
        run: |
          source .venv/bin/activate
          python -m pip install ruff
          ruff check app
      - name: Tests
        run: |
          source .venv/bin/activate
          python -m pip install pytest pytest-cov
          pytest -q --maxfail=1 --disable-warnings

