name: openapi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt uvicorn
      - name: Export OpenAPI
        run: |
          python - <<'PY'
          from app.main import app
          import json, os
          spec = app.openapi()
          os.makedirs('artifacts', exist_ok=True)
          with open('artifacts/openapi.json','w') as f:
              json.dump(spec, f, indent=2)
          print('Wrote artifacts/openapi.json')
          PY
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: artifacts/openapi.json
