name: publish-ecr

on:
  workflow_dispatch:
    inputs:
      region:
        description: AWS region
        required: true
        default: us-east-1
      repository:
        description: ECR repository name
        required: true
      tag:
        description: Image tag to publish
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ github.event.inputs.region }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Pull from GHCR and push to ECR
        env:
          GHCR_IMAGE: ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.inputs.repository }}
        run: |
          docker pull "$GHCR_IMAGE"
          docker tag "$GHCR_IMAGE" "$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.tag }}"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.tag }}"
