name: Release build and publish

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build_publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_API: ghcr.io/${{ github.repository }}-api
      IMAGE_SERVER: ghcr.io/${{ github.repository }}-server
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_API }}:${{ env.VERSION }}
            ${{ env.IMAGE_API }}:latest
          build-args: |
            BUILD_ENV=production

      - name: Build and push legacy server image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_SERVER }}:${{ env.VERSION }}
            ${{ env.IMAGE_SERVER }}:latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Export OpenAPI from FastAPI
        run: |
          python -m pip install fastapi uvicorn pydantic sqlalchemy
          python scripts/export_openapi.py app.main:app integration/openapi.json

      - name: Generate Postman collection
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: |
          npm i -g openapi-to-postmanv2
          openapi2postmanv2 -s integration/openapi.json -o integration/postman/KasiConnect.postman_collection.json -p

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            integration/openapi.json
            integration/postman/KasiConnect.postman_collection.json
            integration/examples/webhooks/librenms.json
            integration/examples/webhooks/zabbix.json

